// // src/app/layout.tsx
// import Footer from "@/components/layout/Footer";
// import GetQuote from "@/components/layout/GetQuote";
// import { DefaultNavbar } from "@/components/layout/navbar";
// import { navbarConfig } from "@/config/navbarConfig";
import React from "react";
// import { Providers } from "./providers";
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import { Providers } from "./providers";
// import { DefaultNavbar } from "@/components/layout/navbar";
// import { navbarConfig } from "@/config/navbarConfig";
// import Footer from "@/components/layout/Footer";
// import GetQuote from "@/components/layout/GetQuote";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Safe Tech",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Providers>
//           <DefaultNavbar mainNav={navbarConfig} />
//           {children}
//           <Footer />
//           <GetQuote />
//         </Providers>
//       </body>
//     </html>
//   );
// }


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}