import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { DefaultNavbar } from "@/components/layout/navbar";
import { navbarConfig } from "@/config/navbarConfig";
import Footer from "@/components/layout/Footer";
import GetQuote from "@/components/layout/GetQuote";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Safe Tech",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params: { locale }
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    // Providing all messages to the client side is the easiest way to get started
    const messages = await getMessages({ locale });

    return (
        <html lang={locale}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Providers>
                    <NextIntlClientProvider messages={messages}>
                        <DefaultNavbar mainNav={navbarConfig} />
                        {children}
                        <Footer />
                        <GetQuote />
                    </NextIntlClientProvider>
                </Providers>
            </body>
        </html>
    );
}